{
 "title": "digitalStrom",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "dss_appartment_consumption" }
   ]
  },
  {
   "title": "Power consumption",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "dss_circuit_consumption", "legendFormat": "{{ circuit }}" }
   ]
  },
  {
   "title": "Power consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watt" }
   ],
   "targets": [
    { "expr": "dss_circuit_consumption", "legendFormat": "{{ circuit }}" }
   ]
  },
  {
   "title": "Devices status",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "dss_device_is_present == 0" }
   ]
  }
 ]
}